import Foundation

struct FilmLibrary {
    let presets: [FilmPreset] = [
        FilmPreset(
            id: "human-warm-400",
            name: "Humanist Color 400",
            shortName: "Humanist",
            iso: 400,
            description: "A 35mm observer roll for cafes, markets, and quiet street scenes: honeyed highlights, clean greens, and forgiving midtones.",
            suitableScenes: ["Street", "Cafe", "Market"],
            exposureBias: 0.05,
            temperatureShift: 300,
            tintShift: 4,
            contrast: 1.02,
            brightness: 0.018,
            saturation: 1.02,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.045),
                p1: CurvePoint(x: 0.22, y: 0.198),
                p2: CurvePoint(x: 0.50, y: 0.525),
                p3: CurvePoint(x: 0.80, y: 0.842),
                p4: CurvePoint(x: 1.00, y: 0.960)
            ),
            grainAmount: 0.20,
            grainSize: 1.05,
            vignetteAmount: 0.22,
            halationAmount: 0.08,
            lightLeakAmount: 0.010,
            timestampColorHex: "#D89948",
            borderStyle: .none,
            localizedName: "街头观察 400",
            localizedShortName: "观察者",
            cameraName: "Observer 35 Compact",
            localizedCameraName: "Observer 35 袖珍机",
            category: .featured,
            localizedDescription: "35mm 观察者胶卷：适合咖啡馆、市集和安静街景，蜂蜜色高光、干净绿色和宽容中间调。",
            localizedSuitableScenes: ["街头", "咖啡馆", "市集"]
        ),
        FilmPreset(
            id: "human-vignette-800",
            name: "Underpass 800",
            shortName: "Underpass",
            iso: 800,
            description: "A fast night-walk roll with tunnel-like lens falloff, deeper blacks, subdued color, and a small pool of light in the center.",
            suitableScenes: ["Night Street", "Subway", "Gallery"],
            exposureBias: -0.08,
            temperatureShift: 120,
            tintShift: -5,
            contrast: 1.26,
            brightness: -0.018,
            saturation: 0.82,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.006),
                p1: CurvePoint(x: 0.20, y: 0.096),
                p2: CurvePoint(x: 0.50, y: 0.470),
                p3: CurvePoint(x: 0.78, y: 0.895),
                p4: CurvePoint(x: 1.00, y: 0.982)
            ),
            grainAmount: 0.34,
            grainSize: 1.32,
            vignetteAmount: 0.66,
            halationAmount: 0.04,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C58B43",
            borderStyle: .none,
            localizedName: "暗廊夜行 800",
            localizedShortName: "暗廊",
            cameraName: "Low-Light 35",
            localizedCameraName: "低照度 35",
            category: .featured,
            localizedDescription: "高速夜行胶卷：镜头像暗廊一样压住边缘，黑位更深，中心留一小块光。",
            localizedSuitableScenes: ["夜街", "地铁", "展馆"]
        ),
        FilmPreset(
            id: "muse-portrait-400",
            name: "Atelier Skin 400",
            shortName: "Atelier",
            iso: 400,
            description: "A studio-leaning portrait roll with creamy skin, low contrast, lifted shadows, and protected forehead highlights.",
            suitableScenes: ["Portrait", "Window Light", "Editorial"],
            exposureBias: 0.16,
            temperatureShift: 220,
            tintShift: 12,
            contrast: 0.82,
            brightness: 0.028,
            saturation: 0.94,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.075),
                p1: CurvePoint(x: 0.24, y: 0.275),
                p2: CurvePoint(x: 0.50, y: 0.552),
                p3: CurvePoint(x: 0.82, y: 0.822),
                p4: CurvePoint(x: 1.00, y: 0.932)
            ),
            grainAmount: 0.08,
            grainSize: 0.76,
            vignetteAmount: 0.05,
            halationAmount: 0.08,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C99A73",
            borderStyle: .none,
            localizedName: "柔肤肖像 400",
            localizedShortName: "肖像",
            cameraName: "85mm Portrait SLR",
            localizedCameraName: "85mm 肖像单反",
            category: .portrait,
            localizedDescription: "偏棚拍的人像胶卷：肤色奶油感、低反差、阴影轻抬，额头和鼻梁高光更稳。",
            localizedSuitableScenes: ["肖像", "窗边光", "编辑写真"]
        ),
        FilmPreset(
            id: "sunlit-gold-200",
            name: "Sunlit Gold 200",
            shortName: "Gold 200",
            iso: 200,
            description: "A warm everyday color roll with soft contrast, gentle yellows, and clean daylight skin tones.",
            suitableScenes: ["Daylight", "Travel", "Everyday"],
            exposureBias: 0.08,
            temperatureShift: 420,
            tintShift: 6,
            contrast: 1.08,
            brightness: 0.01,
            saturation: 1.08,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.22, y: 0.18),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.78, y: 0.84),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.16,
            grainSize: 1.0,
            vignetteAmount: 0.18,
            halationAmount: 0.05,
            lightLeakAmount: 0.0,
            timestampColorHex: "#E2A34F",
            borderStyle: .none,
            localizedName: "晴日金彩 200",
            localizedShortName: "金彩 200",
            cameraName: "35mm Daylight Compact",
            localizedCameraName: "35mm 日光袖珍机",
            category: .negative,
            localizedDescription: "温暖的日常彩负，柔和反差、干净日光肤色和轻微金黄色倾向。",
            localizedSuitableScenes: ["日光", "旅行", "日常"]
        ),
        FilmPreset(
            id: "soft-portrait-400",
            name: "Porcelain Negative 400",
            shortName: "Porcelain",
            iso: 400,
            description: "A pale portrait negative for cloudy skin tones: cool whites, soft reds, open shadows, and calm highlight rolloff.",
            suitableScenes: ["Portrait", "Cloudy", "Soft Daylight"],
            exposureBias: 0.07,
            temperatureShift: 140,
            tintShift: 7,
            contrast: 0.90,
            brightness: 0.016,
            saturation: 0.93,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.052),
                p1: CurvePoint(x: 0.24, y: 0.242),
                p2: CurvePoint(x: 0.50, y: 0.525),
                p3: CurvePoint(x: 0.82, y: 0.852),
                p4: CurvePoint(x: 1.00, y: 0.955)
            ),
            grainAmount: 0.17,
            grainSize: 1.0,
            vignetteAmount: 0.10,
            halationAmount: 0.04,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D7A56D",
            borderStyle: .none,
            localizedName: "瓷白彩负 400",
            localizedShortName: "瓷白",
            cameraName: "Portrait Rangefinder 50",
            localizedCameraName: "50mm 人像旁轴",
            category: .portrait,
            localizedDescription: "偏淡的人像彩负：冷白、柔红、阴影打开，高光过渡更安静。",
            localizedSuitableScenes: ["人像", "阴天", "柔和日光"]
        ),
        FilmPreset(
            id: "silver-hp5",
            name: "Silver HP5",
            shortName: "HP5",
            iso: 400,
            description: "A monochrome documentary roll with visible grain, crisp midtones, and tactile shadows.",
            suitableScenes: ["Street", "Architecture", "Documentary"],
            exposureBias: -0.02,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.22,
            brightness: 0.0,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.20, y: 0.13),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.31,
            grainSize: 1.45,
            vignetteAmount: 0.24,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D9D2C6",
            borderStyle: .paper,
            localizedName: "银盐 HP5",
            localizedShortName: "HP5",
            cameraName: "Documentary SLR",
            localizedCameraName: "纪实单反",
            category: .blackWhite,
            localizedDescription: "黑白纪实胶卷，颗粒明显，中间调利落，阴影有触感。",
            localizedSuitableScenes: ["街头", "建筑", "纪实"]
        ),
        FilmPreset(
            id: "green-street-400",
            name: "Green Street 400",
            shortName: "Street 400",
            iso: 400,
            description: "A cooler city roll with green-cyan shadows, punchier contrast, and a documentary street feel.",
            suitableScenes: ["Street", "Cloudy", "City"],
            exposureBias: -0.03,
            temperatureShift: -220,
            tintShift: -7,
            contrast: 1.13,
            brightness: -0.006,
            saturation: 1.03,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.22, y: 0.16),
                p2: CurvePoint(x: 0.50, y: 0.49),
                p3: CurvePoint(x: 0.78, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.22,
            grainSize: 1.05,
            vignetteAmount: 0.20,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D8A24A",
            borderStyle: .none,
            localizedName: "青绿街拍 400",
            localizedShortName: "街拍 400",
            cameraName: "Street 35",
            localizedCameraName: "街拍 35",
            category: .negative,
            localizedDescription: "偏冷的城市胶卷，青绿色阴影、更强反差和纪实街拍感。",
            localizedSuitableScenes: ["街头", "阴天", "城市"]
        ),
        FilmPreset(
            id: "tungsten-800",
            name: "Cinema Tungsten 800T",
            shortName: "800T",
            iso: 800,
            description: "A cinema-night roll for neon and tungsten interiors, with cooler shadows, amber practical lights, and red-orange halation.",
            suitableScenes: ["Night", "Neon", "Interior"],
            exposureBias: 0.06,
            temperatureShift: -620,
            tintShift: 14,
            contrast: 1.12,
            brightness: -0.002,
            saturation: 1.08,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.030),
                p1: CurvePoint(x: 0.24, y: 0.165),
                p2: CurvePoint(x: 0.50, y: 0.495),
                p3: CurvePoint(x: 0.80, y: 0.890),
                p4: CurvePoint(x: 1.00, y: 0.965)
            ),
            grainAmount: 0.40,
            grainSize: 1.45,
            vignetteAmount: 0.25,
            halationAmount: 0.50,
            lightLeakAmount: 0.015,
            timestampColorHex: "#E07A4B",
            borderStyle: .none,
            localizedName: "电影钨丝 800T",
            localizedShortName: "800T",
            cameraName: "Super 35 Tungsten",
            localizedCameraName: "Super 35 钨丝机",
            category: .experimental,
            localizedDescription: "电影夜景钨丝卷：阴影偏冷，室内灯泡保留琥珀色，高光带红橙泛光。",
            localizedSuitableScenes: ["夜景", "霓虹", "室内灯光"]
        ),
        FilmPreset(
            id: "pocket-flash",
            name: "Pocket Flash 400",
            shortName: "Flash 400",
            iso: 400,
            description: "A 27-shot disposable-camera roll with direct flash contrast, punchy party color, and occasional warm edge leak.",
            suitableScenes: ["Party", "Friends", "Table"],
            exposureBias: 0.12,
            temperatureShift: 260,
            tintShift: 2,
            contrast: 1.22,
            brightness: 0.014,
            saturation: 1.20,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.025),
                p1: CurvePoint(x: 0.18, y: 0.110),
                p2: CurvePoint(x: 0.48, y: 0.508),
                p3: CurvePoint(x: 0.78, y: 0.912),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.30,
            grainSize: 1.24,
            vignetteAmount: 0.32,
            halationAmount: 0.10,
            lightLeakAmount: 0.36,
            timestampColorHex: "#EE9D3D",
            borderStyle: .none,
            localizedName: "口袋闪光 400",
            localizedShortName: "闪光 400",
            cameraName: "27-Shot Flash Compact",
            localizedCameraName: "27 张闪光袖珍机",
            category: .camera,
            localizedDescription: "一次性闪光相机卷：直给闪光反差、聚会色彩更跳，边缘偶尔有暖漏光。",
            localizedSuitableScenes: ["派对", "朋友", "餐桌"]
        ),
        FilmPreset(
            id: "ccd-2003",
            name: "Pocket CCD 2003",
            shortName: "CCD 03",
            iso: 160,
            description: "A three-megapixel compact CCD mood with cool whites, narrow highlight latitude, and blunt early-digital color.",
            suitableScenes: ["Campus", "Flash", "Daily"],
            exposureBias: 0.14,
            temperatureShift: -420,
            tintShift: -6,
            contrast: 1.24,
            brightness: 0.006,
            saturation: 0.88,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.00),
                p1: CurvePoint(x: 0.20, y: 0.125),
                p2: CurvePoint(x: 0.48, y: 0.492),
                p3: CurvePoint(x: 0.78, y: 0.925),
                p4: CurvePoint(x: 1.00, y: 1.00)
            ),
            grainAmount: 0.07,
            grainSize: 0.72,
            vignetteAmount: 0.06,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#BFD3DA",
            borderStyle: .none,
            localizedName: "口袋 CCD 2003",
            localizedShortName: "CCD 03",
            cameraName: "3MP CCD Compact",
            localizedCameraName: "300 万像素 CCD",
            category: .digital,
            localizedDescription: "三百万像素 CCD 袖珍机感：冷白、高光宽容度窄，颜色像早期数码一样直接。",
            localizedSuitableScenes: ["校园", "闪光", "日常"]
        ),
        FilmPreset(
            id: "instant-square",
            name: "SX Square 640",
            shortName: "Square",
            iso: 640,
            description: "A square instant pack with raised blacks, creamy whites, thicker dye grain, and a warm paper border.",
            suitableScenes: ["Still Life", "Selfie", "Desk"],
            exposureBias: 0.08,
            temperatureShift: 260,
            tintShift: 6,
            contrast: 0.82,
            brightness: 0.028,
            saturation: 0.86,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.075),
                p1: CurvePoint(x: 0.22, y: 0.255),
                p2: CurvePoint(x: 0.50, y: 0.535),
                p3: CurvePoint(x: 0.82, y: 0.830),
                p4: CurvePoint(x: 1.00, y: 0.930)
            ),
            grainAmount: 0.22,
            grainSize: 1.55,
            vignetteAmount: 0.18,
            halationAmount: 0.09,
            lightLeakAmount: 0.04,
            timestampColorHex: "#9F7B4E",
            borderStyle: .instant,
            localizedName: "方片即影 640",
            localizedShortName: "方片",
            cameraName: "Square Instant 640",
            localizedCameraName: "方片即影 640",
            category: .instant,
            localizedDescription: "方片即影相纸：黑位抬起、白位奶油感、染料颗粒更厚，带暖白相纸边框。",
            localizedSuitableScenes: ["静物", "自拍", "书桌"]
        ),
        FilmPreset(
            id: "hncs-natural",
            name: "H Natural Color 100",
            shortName: "HNCS 100",
            iso: 100,
            description: "A Hasselblad HNCS-like medium-format profile: neutral color, restrained saturation, and unusually smooth highlight separation.",
            suitableScenes: ["Portrait", "Architecture", "Product"],
            exposureBias: 0.0,
            temperatureShift: 40,
            tintShift: 1,
            contrast: 0.95,
            brightness: 0.006,
            saturation: 0.90,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.030),
                p1: CurvePoint(x: 0.25, y: 0.235),
                p2: CurvePoint(x: 0.50, y: 0.51),
                p3: CurvePoint(x: 0.80, y: 0.820),
                p4: CurvePoint(x: 1.00, y: 0.955)
            ),
            grainAmount: 0.03,
            grainSize: 0.70,
            vignetteAmount: 0.05,
            halationAmount: 0.01,
            lightLeakAmount: 0.0,
            timestampColorHex: "#A88D5A",
            borderStyle: .whiteFrame,
            localizedName: "H 自然色 100",
            localizedShortName: "H 自然色",
            cameraName: "H-System Digital Back",
            localizedCameraName: "H 系统数码后背",
            category: .camera,
            localizedDescription: "Hasselblad HNCS-like 中画幅观感：中性色干净、饱和克制，高光分离非常顺。",
            localizedSuitableScenes: ["肖像", "建筑", "产品"]
        ),
        FilmPreset(
            id: "m-rangefinder",
            name: "M Rangefinder",
            shortName: "M Color",
            iso: 400,
            description: "A compact rangefinder-inspired color profile with deep reds, clear micro-contrast, and calm shadows.",
            suitableScenes: ["Street", "Portrait", "Travel"],
            exposureBias: -0.02,
            temperatureShift: 110,
            tintShift: 5,
            contrast: 1.14,
            brightness: -0.004,
            saturation: 1.03,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.015),
                p1: CurvePoint(x: 0.20, y: 0.15),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.985)
            ),
            grainAmount: 0.18,
            grainSize: 1.0,
            vignetteAmount: 0.16,
            halationAmount: 0.06,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D0A05A",
            borderStyle: .whiteFrame,
            localizedName: "M 旁轴色彩",
            localizedShortName: "M 色彩",
            cameraName: "M Rangefinder",
            localizedCameraName: "M 旁轴",
            category: .camera,
            localizedDescription: "旁轴相机启发的彩色风格：红色更深，微反差清晰，阴影克制。",
            localizedSuitableScenes: ["街拍", "人像", "旅行"]
        ),
        FilmPreset(
            id: "t-compact-gold",
            name: "T Compact Gold",
            shortName: "T Gold",
            iso: 200,
            description: "A premium compact-camera mood with warm flash-friendly skin, golden highlights, and tidy contrast.",
            suitableScenes: ["Party", "Travel", "Friends"],
            exposureBias: 0.10,
            temperatureShift: 360,
            tintShift: 4,
            contrast: 1.12,
            brightness: 0.012,
            saturation: 1.11,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.18, y: 0.14),
                p2: CurvePoint(x: 0.48, y: 0.51),
                p3: CurvePoint(x: 0.76, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.20,
            grainSize: 1.0,
            vignetteAmount: 0.18,
            halationAmount: 0.10,
            lightLeakAmount: 0.03,
            timestampColorHex: "#E0A345",
            borderStyle: .whiteFrame,
            localizedName: "T 袖珍金调",
            localizedShortName: "T 金调",
            cameraName: "T Compact",
            localizedCameraName: "T 袖珍机",
            category: .camera,
            localizedDescription: "高级袖珍机氛围：暖肤色、金色高光、适合闪光灯快照。",
            localizedSuitableScenes: ["聚会", "旅行", "朋友"]
        ),
        FilmPreset(
            id: "gr-street-snap",
            name: "GR Street Snap",
            shortName: "GR Snap",
            iso: 800,
            description: "A fast street-snap profile with cool whites, strong midtone contrast, and clean documentary blacks.",
            suitableScenes: ["Street", "Night", "Documentary"],
            exposureBias: -0.05,
            temperatureShift: -260,
            tintShift: -4,
            contrast: 1.24,
            brightness: -0.008,
            saturation: 0.88,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.01),
                p1: CurvePoint(x: 0.18, y: 0.11),
                p2: CurvePoint(x: 0.48, y: 0.48),
                p3: CurvePoint(x: 0.76, y: 0.90),
                p4: CurvePoint(x: 1.00, y: 0.995)
            ),
            grainAmount: 0.18,
            grainSize: 0.9,
            vignetteAmount: 0.12,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C7D2D1",
            borderStyle: .none,
            localizedName: "GR 街拍",
            localizedShortName: "GR",
            cameraName: "GR Pocket",
            localizedCameraName: "GR 街拍机",
            category: .camera,
            localizedDescription: "快速街拍风格：冷白、强中间调反差、黑位干净。",
            localizedSuitableScenes: ["街拍", "夜晚", "纪实"]
        ),
        FilmPreset(
            id: "classic-chrome-x",
            name: "Classic Chrome X",
            shortName: "Chrome X",
            iso: 400,
            description: "Muted documentary color with cyan-green shadows, soft reds, and a dry magazine-like finish.",
            suitableScenes: ["City", "Documentary", "Cafe"],
            exposureBias: -0.02,
            temperatureShift: -180,
            tintShift: -8,
            contrast: 1.04,
            brightness: 0.0,
            saturation: 0.78,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.24, y: 0.20),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.83),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.16,
            grainSize: 1.0,
            vignetteAmount: 0.14,
            halationAmount: 0.02,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C7A76B",
            borderStyle: .none,
            localizedName: "经典铬色 X",
            localizedShortName: "铬色 X",
            cameraName: "X100 Classic",
            localizedCameraName: "X100 经典",
            category: .camera,
            localizedDescription: "低饱和纪实色彩：青绿色阴影、柔和红色、杂志感干燥质地。",
            localizedSuitableScenes: ["城市", "纪实", "咖啡馆"]
        ),
        FilmPreset(
            id: "medium-500c",
            name: "500C Medium",
            shortName: "500C",
            iso: 160,
            description: "A square medium-format look with open shadows, gentle skin, and quiet studio color.",
            suitableScenes: ["Portrait", "Still Life", "Studio"],
            exposureBias: 0.04,
            temperatureShift: 120,
            tintShift: 3,
            contrast: 0.92,
            brightness: 0.018,
            saturation: 0.94,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.045),
                p1: CurvePoint(x: 0.25, y: 0.24),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.82, y: 0.84),
                p4: CurvePoint(x: 1.00, y: 0.96)
            ),
            grainAmount: 0.12,
            grainSize: 1.05,
            vignetteAmount: 0.10,
            halationAmount: 0.04,
            lightLeakAmount: 0.0,
            timestampColorHex: "#9E8052",
            borderStyle: .paper,
            localizedName: "500C 中画幅",
            localizedShortName: "500C",
            cameraName: "500C Medium",
            localizedCameraName: "500C 中画幅",
            category: .camera,
            localizedDescription: "方形中画幅观感：阴影打开、肤色轻柔、棚拍色彩安静。",
            localizedSuitableScenes: ["人像", "静物", "棚拍"]
        ),
        FilmPreset(
            id: "holga-120-dream",
            name: "Holga 120 Dream",
            shortName: "Holga",
            iso: 400,
            description: "A toy 120 camera feel with heavy vignette, softened contrast, random warmth, and edge leak.",
            suitableScenes: ["Travel", "Memory", "Cloudy"],
            exposureBias: 0.08,
            temperatureShift: 300,
            tintShift: 12,
            contrast: 0.86,
            brightness: 0.02,
            saturation: 1.08,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.06),
                p1: CurvePoint(x: 0.22, y: 0.20),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.82, y: 0.82),
                p4: CurvePoint(x: 1.00, y: 0.95)
            ),
            grainAmount: 0.30,
            grainSize: 1.5,
            vignetteAmount: 0.46,
            halationAmount: 0.08,
            lightLeakAmount: 0.22,
            timestampColorHex: "#BA7D4D",
            borderStyle: .paper,
            localizedName: "Holga 120 梦境",
            localizedShortName: "Holga",
            cameraName: "Toy 120",
            localizedCameraName: "120 玩具机",
            category: .experimental,
            localizedDescription: "120 玩具相机感：暗角明显、反差变软、边缘偶发漏光。",
            localizedSuitableScenes: ["旅行", "记忆感", "阴天"]
        ),
        FilmPreset(
            id: "lca-vivid",
            name: "LC-A Vivid",
            shortName: "LC-A",
            iso: 400,
            description: "A lomo-inspired roll with saturated color, tunnel vignette, warm corners, and playful contrast.",
            suitableScenes: ["Travel", "Street", "Sunset"],
            exposureBias: 0.04,
            temperatureShift: 240,
            tintShift: 6,
            contrast: 1.24,
            brightness: 0.0,
            saturation: 1.34,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.015),
                p1: CurvePoint(x: 0.17, y: 0.11),
                p2: CurvePoint(x: 0.48, y: 0.49),
                p3: CurvePoint(x: 0.78, y: 0.91),
                p4: CurvePoint(x: 1.00, y: 0.995)
            ),
            grainAmount: 0.26,
            grainSize: 1.2,
            vignetteAmount: 0.38,
            halationAmount: 0.10,
            lightLeakAmount: 0.12,
            timestampColorHex: "#E99B32",
            borderStyle: .none,
            localizedName: "LC-A 鲜艳",
            localizedShortName: "LC-A",
            cameraName: "LC-A Compact",
            localizedCameraName: "LC-A 袖珍机",
            category: .experimental,
            localizedDescription: "Lomo 启发的胶卷：高饱和、隧道暗角、暖边缘和玩味反差。",
            localizedSuitableScenes: ["旅行", "街拍", "日落"]
        ),
        FilmPreset(
            id: "instant-wide",
            name: "Wide Instant 800",
            shortName: "Wide",
            iso: 800,
            description: "A wide instant pack for group tables and travel notes: creamy highlights, lifted blacks, and a broader paper frame.",
            suitableScenes: ["Friends", "Table", "Travel"],
            exposureBias: 0.10,
            temperatureShift: 220,
            tintShift: 4,
            contrast: 0.84,
            brightness: 0.028,
            saturation: 0.90,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.078),
                p1: CurvePoint(x: 0.24, y: 0.262),
                p2: CurvePoint(x: 0.50, y: 0.525),
                p3: CurvePoint(x: 0.82, y: 0.828),
                p4: CurvePoint(x: 1.00, y: 0.925)
            ),
            grainAmount: 0.22,
            grainSize: 1.50,
            vignetteAmount: 0.12,
            halationAmount: 0.10,
            lightLeakAmount: 0.04,
            timestampColorHex: "#806B48",
            borderStyle: .instant,
            localizedName: "宽幅即影 800",
            localizedShortName: "宽幅",
            cameraName: "Wide Instant 210",
            localizedCameraName: "Wide 210 即影机",
            category: .instant,
            localizedDescription: "宽幅即影相纸：适合多人餐桌和旅行札记，高光奶油感、黑位抬起，边框更宽。",
            localizedSuitableScenes: ["朋友", "餐桌", "旅行"]
        ),
        FilmPreset(
            id: "sx-fade",
            name: "Faded SX 160",
            shortName: "SX",
            iso: 160,
            description: "A folding instant-camera pack with pastel dye fade, soft-focus impression, and a warm ivory frame.",
            suitableScenes: ["Home", "Flowers", "Selfie"],
            exposureBias: 0.14,
            temperatureShift: 380,
            tintShift: 12,
            contrast: 0.74,
            brightness: 0.034,
            saturation: 0.74,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.092),
                p1: CurvePoint(x: 0.25, y: 0.285),
                p2: CurvePoint(x: 0.50, y: 0.548),
                p3: CurvePoint(x: 0.82, y: 0.805),
                p4: CurvePoint(x: 1.00, y: 0.900)
            ),
            grainAmount: 0.18,
            grainSize: 1.6,
            vignetteAmount: 0.10,
            halationAmount: 0.14,
            lightLeakAmount: 0.02,
            timestampColorHex: "#96724D",
            borderStyle: .instant,
            localizedName: "SX 褪彩 160",
            localizedShortName: "SX",
            cameraName: "Folding SX Instant",
            localizedCameraName: "SX 折叠即影机",
            category: .instant,
            localizedDescription: "折叠即影机相纸：粉彩染料褪色、柔焦感明显，配暖象牙白边框。",
            localizedSuitableScenes: ["居家", "花草", "自拍"]
        ),
        FilmPreset(
            id: "half-frame-diary",
            name: "Half Frame Diary",
            shortName: "Half",
            iso: 400,
            description: "A half-frame diary camera style with vertical composition, warm date color, and casual grain.",
            suitableScenes: ["Daily", "Travel", "Street"],
            exposureBias: 0.02,
            temperatureShift: 180,
            tintShift: 2,
            contrast: 1.06,
            brightness: 0.006,
            saturation: 1.02,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.22, y: 0.17),
                p2: CurvePoint(x: 0.50, y: 0.51),
                p3: CurvePoint(x: 0.79, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.23,
            grainSize: 1.1,
            vignetteAmount: 0.19,
            halationAmount: 0.05,
            lightLeakAmount: 0.07,
            timestampColorHex: "#D69343",
            borderStyle: .whiteFrame,
            localizedName: "半格日记",
            localizedShortName: "半格",
            cameraName: "Half Frame",
            localizedCameraName: "半格相机",
            category: .camera,
            localizedDescription: "半格日记相机风格：竖向构图、暖色日期戳和随性的颗粒。",
            localizedSuitableScenes: ["日常", "旅行", "街拍"]
        ),
        FilmPreset(
            id: "ektar-vivid-100",
            name: "Ektar Vivid 100",
            shortName: "Vivid 100",
            iso: 100,
            description: "A vivid fine-grain color negative style with clean skies, saturated reds, and crisp daylight contrast.",
            suitableScenes: ["Landscape", "Cars", "Daylight"],
            exposureBias: -0.01,
            temperatureShift: 90,
            tintShift: 3,
            contrast: 1.18,
            brightness: 0.0,
            saturation: 1.26,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.01),
                p1: CurvePoint(x: 0.18, y: 0.13),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.89),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.10,
            grainSize: 0.85,
            vignetteAmount: 0.10,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D08B33",
            borderStyle: .none,
            localizedName: "鲜艳彩负 100",
            localizedShortName: "鲜艳100",
            cameraName: "Daylight Negative",
            localizedCameraName: "日光彩负",
            category: .negative,
            localizedDescription: "细颗粒高饱和彩负：天空干净、红色饱满、日光反差清晰。",
            localizedSuitableScenes: ["风景", "汽车", "日光"]
        ),
        FilmPreset(
            id: "tri-x-street",
            name: "Tri-X Street",
            shortName: "Tri-X",
            iso: 400,
            description: "A classic black-and-white street roll with punchy contrast, bright whites, and gritty midtones.",
            suitableScenes: ["Street", "Documentary", "Rain"],
            exposureBias: -0.04,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.34,
            brightness: -0.004,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.015),
                p1: CurvePoint(x: 0.18, y: 0.10),
                p2: CurvePoint(x: 0.48, y: 0.48),
                p3: CurvePoint(x: 0.77, y: 0.91),
                p4: CurvePoint(x: 1.00, y: 0.995)
            ),
            grainAmount: 0.38,
            grainSize: 1.35,
            vignetteAmount: 0.20,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D8D0C1",
            borderStyle: .paper,
            localizedName: "Tri-X 街头",
            localizedShortName: "Tri-X",
            cameraName: "Street SLR",
            localizedCameraName: "街头单反",
            category: .blackWhite,
            localizedDescription: "经典黑白街拍卷：反差有力、白位明亮、中间调粗粝。",
            localizedSuitableScenes: ["街拍", "纪实", "雨天"]
        ),
        FilmPreset(
            id: "cyber-ccd-blue",
            name: "Blue CCD Night 200",
            shortName: "CCD Night",
            iso: 200,
            description: "A pocket CCD night profile with blue-white highlights, clipped flash faces, and compact-camera bluntness.",
            suitableScenes: ["Flash", "Night", "Karaoke"],
            exposureBias: 0.15,
            temperatureShift: -620,
            tintShift: -8,
            contrast: 1.32,
            brightness: 0.0,
            saturation: 0.82,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.00),
                p1: CurvePoint(x: 0.18, y: 0.108),
                p2: CurvePoint(x: 0.48, y: 0.492),
                p3: CurvePoint(x: 0.76, y: 0.940),
                p4: CurvePoint(x: 1.00, y: 1.00)
            ),
            grainAmount: 0.07,
            grainSize: 0.72,
            vignetteAmount: 0.07,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#BFD8E5",
            borderStyle: .none,
            localizedName: "蓝白 CCD 200",
            localizedShortName: "CCD 夜拍",
            cameraName: "Night CCD Compact",
            localizedCameraName: "夜拍 CCD 袖珍机",
            category: .digital,
            localizedDescription: "袖珍 CCD 夜拍配置：蓝白高光、闪光灯脸部白位截断，保留早期卡片机的直硬感。",
            localizedSuitableScenes: ["闪光", "夜晚", "KTV"]
        ),
        FilmPreset(
            id: "superia-green",
            name: "Superia Green",
            shortName: "Superia",
            iso: 400,
            description: "A consumer color roll with green shadows, lively blues, and bright vacation snapshots.",
            suitableScenes: ["Travel", "Beach", "Everyday"],
            exposureBias: 0.05,
            temperatureShift: -80,
            tintShift: -10,
            contrast: 1.10,
            brightness: 0.008,
            saturation: 1.16,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.025),
                p1: CurvePoint(x: 0.20, y: 0.16),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.78, y: 0.87),
                p4: CurvePoint(x: 1.00, y: 0.985)
            ),
            grainAmount: 0.24,
            grainSize: 1.1,
            vignetteAmount: 0.18,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#E0A14A",
            borderStyle: .none,
            localizedName: "Superia 绿调",
            localizedShortName: "绿调",
            cameraName: "Consumer 35",
            localizedCameraName: "家用 35mm",
            category: .negative,
            localizedDescription: "家用彩负感：绿色阴影、蓝色活泼、明亮度假快照。",
            localizedSuitableScenes: ["旅行", "海边", "日常"]
        ),
        FilmPreset(
            id: "noir-soft",
            name: "Noir Cine 1600",
            shortName: "Noir 16",
            iso: 1600,
            description: "A pushed monochrome night roll with glowing signs, dense cinema shadows, and coarse silver grain.",
            suitableScenes: ["Night", "Portrait", "Window"],
            exposureBias: 0.04,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.12,
            brightness: 0.0,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.040),
                p1: CurvePoint(x: 0.24, y: 0.175),
                p2: CurvePoint(x: 0.50, y: 0.492),
                p3: CurvePoint(x: 0.82, y: 0.875),
                p4: CurvePoint(x: 1.00, y: 0.968)
            ),
            grainAmount: 0.48,
            grainSize: 1.72,
            vignetteAmount: 0.32,
            halationAmount: 0.20,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D0C8BB",
            borderStyle: .paper,
            localizedName: "黑白电影 1600",
            localizedShortName: "Noir 16",
            cameraName: "Noir Cine 35",
            localizedCameraName: "Noir Cine 35",
            category: .blackWhite,
            localizedDescription: "增感黑白夜景卷：招牌高光发亮，阴影更像电影黑位，银盐颗粒更粗。",
            localizedSuitableScenes: ["夜晚", "人像", "窗边"]
        )
    ]

    var presetIds: Set<String> {
        Set(presets.map(\.id))
    }

    var cameraProfiles: [FilmCameraProfile] {
        presets.map(\.cameraProfile)
    }

    var missingCameraProfileIds: Set<String> {
        FilmCameraProfileCatalog.missingProfileIds(in: presets)
    }

    func presets(matching category: FilmCategory, favoriteIds: Set<String>) -> [FilmPreset] {
        switch category {
        case .favorites:
            return favoritePresets(with: favoriteIds)
        default:
            return presets.filter { $0.category == category }
        }
    }

    func favoritePresets(with favoriteIds: Set<String>) -> [FilmPreset] {
        presets.filter { favoriteIds.contains($0.id) }
    }
}
