import Foundation

struct FilmLibrary {
    let presets: [FilmPreset] = [
        FilmPreset(
            id: "sunlit-gold-200",
            name: "Sunlit Gold 200",
            shortName: "Gold 200",
            iso: 200,
            description: "A warm everyday color roll with soft contrast, gentle yellows, and clean daylight skin tones.",
            suitableScenes: ["Daylight", "Travel", "Everyday"],
            exposureBias: 0.08,
            temperatureShift: 420,
            tintShift: 6,
            contrast: 1.08,
            brightness: 0.01,
            saturation: 1.08,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.22, y: 0.18),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.78, y: 0.84),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.16,
            grainSize: 1.0,
            vignetteAmount: 0.18,
            halationAmount: 0.05,
            lightLeakAmount: 0.0,
            timestampColorHex: "#E2A34F",
            borderStyle: .none,
            localizedName: "晴日金彩 200",
            localizedShortName: "金彩 200",
            cameraName: "35mm Daylight Compact",
            localizedCameraName: "35mm 日光袖珍机",
            category: .negative,
            localizedDescription: "温暖的日常彩负，柔和反差、干净日光肤色和轻微金黄色倾向。",
            localizedSuitableScenes: ["日光", "旅行", "日常"]
        ),
        FilmPreset(
            id: "soft-portrait-400",
            name: "Soft Portrait 400",
            shortName: "Portrait 400",
            iso: 400,
            description: "Low-contrast color negative look with lifted shadows, calm highlights, and forgiving skin tones.",
            suitableScenes: ["Portrait", "Cloudy", "Indoor"],
            exposureBias: 0.04,
            temperatureShift: 180,
            tintShift: 8,
            contrast: 0.94,
            brightness: 0.012,
            saturation: 0.96,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.04),
                p1: CurvePoint(x: 0.24, y: 0.23),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.82, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.20,
            grainSize: 1.1,
            vignetteAmount: 0.12,
            halationAmount: 0.04,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D7A56D",
            borderStyle: .none,
            localizedName: "柔和人像 400",
            localizedShortName: "人像 400",
            cameraName: "Portrait Rangefinder",
            localizedCameraName: "人像旁轴",
            category: .negative,
            localizedDescription: "低反差彩负风格，抬起阴影、压住高光，让肤色更宽容。",
            localizedSuitableScenes: ["人像", "阴天", "室内"]
        ),
        FilmPreset(
            id: "silver-hp5",
            name: "Silver HP5",
            shortName: "HP5",
            iso: 400,
            description: "A monochrome documentary roll with visible grain, crisp midtones, and tactile shadows.",
            suitableScenes: ["Street", "Architecture", "Documentary"],
            exposureBias: -0.02,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.22,
            brightness: 0.0,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.20, y: 0.13),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.31,
            grainSize: 1.45,
            vignetteAmount: 0.24,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D9D2C6",
            borderStyle: .paper,
            localizedName: "银盐 HP5",
            localizedShortName: "HP5",
            cameraName: "Documentary SLR",
            localizedCameraName: "纪实单反",
            category: .blackWhite,
            localizedDescription: "黑白纪实胶卷，颗粒明显，中间调利落，阴影有触感。",
            localizedSuitableScenes: ["街头", "建筑", "纪实"]
        ),
        FilmPreset(
            id: "green-street-400",
            name: "Green Street 400",
            shortName: "Street 400",
            iso: 400,
            description: "A cooler city roll with green-cyan shadows, punchier contrast, and a documentary street feel.",
            suitableScenes: ["Street", "Cloudy", "City"],
            exposureBias: -0.03,
            temperatureShift: -220,
            tintShift: -7,
            contrast: 1.13,
            brightness: -0.006,
            saturation: 1.03,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.22, y: 0.16),
                p2: CurvePoint(x: 0.50, y: 0.49),
                p3: CurvePoint(x: 0.78, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.22,
            grainSize: 1.05,
            vignetteAmount: 0.20,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D8A24A",
            borderStyle: .none,
            localizedName: "青绿街拍 400",
            localizedShortName: "街拍 400",
            cameraName: "Street 35",
            localizedCameraName: "街拍 35",
            category: .negative,
            localizedDescription: "偏冷的城市胶卷，青绿色阴影、更强反差和纪实街拍感。",
            localizedSuitableScenes: ["街头", "阴天", "城市"]
        ),
        FilmPreset(
            id: "tungsten-800",
            name: "Tungsten 800",
            shortName: "Tungsten",
            iso: 800,
            description: "A night roll for neon, tungsten interiors, and red-orange highlight bloom.",
            suitableScenes: ["Night", "Neon", "Indoor"],
            exposureBias: 0.10,
            temperatureShift: -520,
            tintShift: 12,
            contrast: 1.08,
            brightness: 0.004,
            saturation: 1.12,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.04),
                p1: CurvePoint(x: 0.24, y: 0.18),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.80, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.36,
            grainSize: 1.4,
            vignetteAmount: 0.22,
            halationAmount: 0.42,
            lightLeakAmount: 0.02,
            timestampColorHex: "#E07A4B",
            borderStyle: .none,
            localizedName: "钨丝夜色 800",
            localizedShortName: "钨丝",
            cameraName: "Cinema Tungsten",
            localizedCameraName: "电影钨丝机",
            category: .experimental,
            localizedDescription: "面向霓虹和室内钨丝灯的夜景卷，带红橙高光泛光。",
            localizedSuitableScenes: ["夜景", "霓虹", "室内"]
        ),
        FilmPreset(
            id: "pocket-flash",
            name: "Pocket Flash",
            shortName: "Flash",
            iso: 400,
            description: "A compact disposable-camera look with hard contrast, casual saturation, and occasional edge leak.",
            suitableScenes: ["Party", "Friends", "Snapshot"],
            exposureBias: 0.12,
            temperatureShift: 260,
            tintShift: 2,
            contrast: 1.18,
            brightness: 0.018,
            saturation: 1.18,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.18, y: 0.12),
                p2: CurvePoint(x: 0.48, y: 0.51),
                p3: CurvePoint(x: 0.78, y: 0.90),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.28,
            grainSize: 1.2,
            vignetteAmount: 0.30,
            halationAmount: 0.12,
            lightLeakAmount: 0.34,
            timestampColorHex: "#EE9D3D",
            borderStyle: .none,
            localizedName: "口袋闪光",
            localizedShortName: "闪光",
            cameraName: "Disposable Flash",
            localizedCameraName: "一次性闪光机",
            category: .camera,
            localizedDescription: "一次性相机的直接感，硬反差、随手饱和度和偶发边缘漏光。",
            localizedSuitableScenes: ["派对", "朋友", "随拍"]
        ),
        FilmPreset(
            id: "ccd-2003",
            name: "CCD 2003",
            shortName: "CCD",
            iso: 160,
            description: "A clean early-digital compact camera mood with cool whites, clipped highlights, and direct color.",
            suitableScenes: ["Campus", "Indoor", "Daily"],
            exposureBias: 0.16,
            temperatureShift: -340,
            tintShift: -4,
            contrast: 1.20,
            brightness: 0.012,
            saturation: 0.92,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.00),
                p1: CurvePoint(x: 0.20, y: 0.14),
                p2: CurvePoint(x: 0.48, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.91),
                p4: CurvePoint(x: 1.00, y: 1.00)
            ),
            grainAmount: 0.10,
            grainSize: 0.8,
            vignetteAmount: 0.08,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C8D6DA",
            borderStyle: .none,
            localizedName: "CCD 2003",
            localizedShortName: "CCD",
            cameraName: "CCD Compact 2003",
            localizedCameraName: "2003 CCD 袖珍机",
            category: .digital,
            localizedDescription: "早期数码卡片机感，冷白、直接色彩和略硬的高光。",
            localizedSuitableScenes: ["校园", "室内", "日常"]
        ),
        FilmPreset(
            id: "instant-square",
            name: "Instant Square",
            shortName: "Instant",
            iso: 640,
            description: "A soft instant-photo preset with square framing, warm paper border, and relaxed contrast.",
            suitableScenes: ["Still Life", "Selfie", "Home"],
            exposureBias: 0.06,
            temperatureShift: 240,
            tintShift: 5,
            contrast: 0.88,
            brightness: 0.02,
            saturation: 0.90,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.05),
                p1: CurvePoint(x: 0.22, y: 0.23),
                p2: CurvePoint(x: 0.50, y: 0.53),
                p3: CurvePoint(x: 0.82, y: 0.85),
                p4: CurvePoint(x: 1.00, y: 0.96)
            ),
            grainAmount: 0.18,
            grainSize: 1.35,
            vignetteAmount: 0.16,
            halationAmount: 0.06,
            lightLeakAmount: 0.03,
            timestampColorHex: "#9F7B4E",
            borderStyle: .instant,
            localizedName: "方形即影",
            localizedShortName: "即影",
            cameraName: "Instant Square",
            localizedCameraName: "方形拍立得",
            category: .instant,
            localizedDescription: "柔和的拍立得观感，方形构图、暖白相纸边框和松弛反差。",
            localizedSuitableScenes: ["静物", "自拍", "居家"]
        ),
        FilmPreset(
            id: "hncs-natural",
            name: "HNCS Natural",
            shortName: "HNCS",
            iso: 100,
            description: "A Hasselblad Natural Colour Solution-inspired look: clean neutrals, restrained saturation, and very smooth highlight separation.",
            suitableScenes: ["Portrait", "Architecture", "Landscape"],
            exposureBias: 0.02,
            temperatureShift: 60,
            tintShift: 2,
            contrast: 0.98,
            brightness: 0.004,
            saturation: 0.94,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.025),
                p1: CurvePoint(x: 0.25, y: 0.23),
                p2: CurvePoint(x: 0.50, y: 0.51),
                p3: CurvePoint(x: 0.80, y: 0.83),
                p4: CurvePoint(x: 1.00, y: 0.965)
            ),
            grainAmount: 0.06,
            grainSize: 0.8,
            vignetteAmount: 0.08,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#A88D5A",
            borderStyle: .whiteFrame,
            localizedName: "HNCS 自然色",
            localizedShortName: "HNCS",
            cameraName: "H-System Natural",
            localizedCameraName: "哈苏自然色",
            category: .camera,
            localizedDescription: "受哈苏自然色彩观感启发：中性色干净、饱和克制、高光过渡很顺。",
            localizedSuitableScenes: ["人像", "建筑", "风景"]
        ),
        FilmPreset(
            id: "m-rangefinder",
            name: "M Rangefinder",
            shortName: "M Color",
            iso: 400,
            description: "A compact rangefinder-inspired color profile with deep reds, clear micro-contrast, and calm shadows.",
            suitableScenes: ["Street", "Portrait", "Travel"],
            exposureBias: -0.02,
            temperatureShift: 110,
            tintShift: 5,
            contrast: 1.14,
            brightness: -0.004,
            saturation: 1.03,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.015),
                p1: CurvePoint(x: 0.20, y: 0.15),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.985)
            ),
            grainAmount: 0.18,
            grainSize: 1.0,
            vignetteAmount: 0.16,
            halationAmount: 0.06,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D0A05A",
            borderStyle: .whiteFrame,
            localizedName: "M 旁轴色彩",
            localizedShortName: "M 色彩",
            cameraName: "M Rangefinder",
            localizedCameraName: "M 旁轴",
            category: .camera,
            localizedDescription: "旁轴相机启发的彩色风格：红色更深，微反差清晰，阴影克制。",
            localizedSuitableScenes: ["街拍", "人像", "旅行"]
        ),
        FilmPreset(
            id: "t-compact-gold",
            name: "T Compact Gold",
            shortName: "T Gold",
            iso: 200,
            description: "A premium compact-camera mood with warm flash-friendly skin, golden highlights, and tidy contrast.",
            suitableScenes: ["Party", "Travel", "Friends"],
            exposureBias: 0.10,
            temperatureShift: 360,
            tintShift: 4,
            contrast: 1.12,
            brightness: 0.012,
            saturation: 1.11,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.18, y: 0.14),
                p2: CurvePoint(x: 0.48, y: 0.51),
                p3: CurvePoint(x: 0.76, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.20,
            grainSize: 1.0,
            vignetteAmount: 0.18,
            halationAmount: 0.10,
            lightLeakAmount: 0.03,
            timestampColorHex: "#E0A345",
            borderStyle: .whiteFrame,
            localizedName: "T 袖珍金调",
            localizedShortName: "T 金调",
            cameraName: "T Compact",
            localizedCameraName: "T 袖珍机",
            category: .camera,
            localizedDescription: "高级袖珍机氛围：暖肤色、金色高光、适合闪光灯快照。",
            localizedSuitableScenes: ["聚会", "旅行", "朋友"]
        ),
        FilmPreset(
            id: "gr-street-snap",
            name: "GR Street Snap",
            shortName: "GR Snap",
            iso: 800,
            description: "A fast street-snap profile with cool whites, strong midtone contrast, and clean documentary blacks.",
            suitableScenes: ["Street", "Night", "Documentary"],
            exposureBias: -0.05,
            temperatureShift: -260,
            tintShift: -4,
            contrast: 1.24,
            brightness: -0.008,
            saturation: 0.88,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.01),
                p1: CurvePoint(x: 0.18, y: 0.11),
                p2: CurvePoint(x: 0.48, y: 0.48),
                p3: CurvePoint(x: 0.76, y: 0.90),
                p4: CurvePoint(x: 1.00, y: 0.995)
            ),
            grainAmount: 0.18,
            grainSize: 0.9,
            vignetteAmount: 0.12,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C7D2D1",
            borderStyle: .none,
            localizedName: "GR 街拍",
            localizedShortName: "GR",
            cameraName: "GR Pocket",
            localizedCameraName: "GR 街拍机",
            category: .camera,
            localizedDescription: "快速街拍风格：冷白、强中间调反差、黑位干净。",
            localizedSuitableScenes: ["街拍", "夜晚", "纪实"]
        ),
        FilmPreset(
            id: "classic-chrome-x",
            name: "Classic Chrome X",
            shortName: "Chrome X",
            iso: 400,
            description: "Muted documentary color with cyan-green shadows, soft reds, and a dry magazine-like finish.",
            suitableScenes: ["City", "Documentary", "Cafe"],
            exposureBias: -0.02,
            temperatureShift: -180,
            tintShift: -8,
            contrast: 1.04,
            brightness: 0.0,
            saturation: 0.78,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.24, y: 0.20),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.83),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.16,
            grainSize: 1.0,
            vignetteAmount: 0.14,
            halationAmount: 0.02,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C7A76B",
            borderStyle: .none,
            localizedName: "经典铬色 X",
            localizedShortName: "铬色 X",
            cameraName: "X100 Classic",
            localizedCameraName: "X100 经典",
            category: .camera,
            localizedDescription: "低饱和纪实色彩：青绿色阴影、柔和红色、杂志感干燥质地。",
            localizedSuitableScenes: ["城市", "纪实", "咖啡馆"]
        ),
        FilmPreset(
            id: "medium-500c",
            name: "500C Medium",
            shortName: "500C",
            iso: 160,
            description: "A square medium-format look with open shadows, gentle skin, and quiet studio color.",
            suitableScenes: ["Portrait", "Still Life", "Studio"],
            exposureBias: 0.04,
            temperatureShift: 120,
            tintShift: 3,
            contrast: 0.92,
            brightness: 0.018,
            saturation: 0.94,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.045),
                p1: CurvePoint(x: 0.25, y: 0.24),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.82, y: 0.84),
                p4: CurvePoint(x: 1.00, y: 0.96)
            ),
            grainAmount: 0.12,
            grainSize: 1.05,
            vignetteAmount: 0.10,
            halationAmount: 0.04,
            lightLeakAmount: 0.0,
            timestampColorHex: "#9E8052",
            borderStyle: .paper,
            localizedName: "500C 中画幅",
            localizedShortName: "500C",
            cameraName: "500C Medium",
            localizedCameraName: "500C 中画幅",
            category: .camera,
            localizedDescription: "方形中画幅观感：阴影打开、肤色轻柔、棚拍色彩安静。",
            localizedSuitableScenes: ["人像", "静物", "棚拍"]
        ),
        FilmPreset(
            id: "holga-120-dream",
            name: "Holga 120 Dream",
            shortName: "Holga",
            iso: 400,
            description: "A toy 120 camera feel with heavy vignette, softened contrast, random warmth, and edge leak.",
            suitableScenes: ["Travel", "Memory", "Cloudy"],
            exposureBias: 0.08,
            temperatureShift: 300,
            tintShift: 12,
            contrast: 0.86,
            brightness: 0.02,
            saturation: 1.08,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.06),
                p1: CurvePoint(x: 0.22, y: 0.20),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.82, y: 0.82),
                p4: CurvePoint(x: 1.00, y: 0.95)
            ),
            grainAmount: 0.30,
            grainSize: 1.5,
            vignetteAmount: 0.46,
            halationAmount: 0.08,
            lightLeakAmount: 0.22,
            timestampColorHex: "#BA7D4D",
            borderStyle: .paper,
            localizedName: "Holga 120 梦境",
            localizedShortName: "Holga",
            cameraName: "Toy 120",
            localizedCameraName: "120 玩具机",
            category: .experimental,
            localizedDescription: "120 玩具相机感：暗角明显、反差变软、边缘偶发漏光。",
            localizedSuitableScenes: ["旅行", "记忆感", "阴天"]
        ),
        FilmPreset(
            id: "lca-vivid",
            name: "LC-A Vivid",
            shortName: "LC-A",
            iso: 400,
            description: "A lomo-inspired roll with saturated color, tunnel vignette, warm corners, and playful contrast.",
            suitableScenes: ["Travel", "Street", "Sunset"],
            exposureBias: 0.04,
            temperatureShift: 240,
            tintShift: 6,
            contrast: 1.24,
            brightness: 0.0,
            saturation: 1.34,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.015),
                p1: CurvePoint(x: 0.17, y: 0.11),
                p2: CurvePoint(x: 0.48, y: 0.49),
                p3: CurvePoint(x: 0.78, y: 0.91),
                p4: CurvePoint(x: 1.00, y: 0.995)
            ),
            grainAmount: 0.26,
            grainSize: 1.2,
            vignetteAmount: 0.38,
            halationAmount: 0.10,
            lightLeakAmount: 0.12,
            timestampColorHex: "#E99B32",
            borderStyle: .none,
            localizedName: "LC-A 鲜艳",
            localizedShortName: "LC-A",
            cameraName: "LC-A Compact",
            localizedCameraName: "LC-A 袖珍机",
            category: .experimental,
            localizedDescription: "Lomo 启发的胶卷：高饱和、隧道暗角、暖边缘和玩味反差。",
            localizedSuitableScenes: ["旅行", "街拍", "日落"]
        ),
        FilmPreset(
            id: "instant-wide",
            name: "Instant Wide",
            shortName: "Wide",
            iso: 800,
            description: "A wide instant-photo frame with creamy highlights, lifted blacks, and a handwritten-camera label.",
            suitableScenes: ["Friends", "Table", "Travel"],
            exposureBias: 0.08,
            temperatureShift: 220,
            tintShift: 4,
            contrast: 0.86,
            brightness: 0.024,
            saturation: 0.92,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.07),
                p1: CurvePoint(x: 0.24, y: 0.25),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.82, y: 0.84),
                p4: CurvePoint(x: 1.00, y: 0.94)
            ),
            grainAmount: 0.20,
            grainSize: 1.45,
            vignetteAmount: 0.14,
            halationAmount: 0.08,
            lightLeakAmount: 0.04,
            timestampColorHex: "#806B48",
            borderStyle: .instant,
            localizedName: "宽幅拍立得",
            localizedShortName: "宽幅",
            cameraName: "Instant Wide",
            localizedCameraName: "宽幅拍立得",
            category: .instant,
            localizedDescription: "宽幅即影边框，高光奶油感、黑位抬起，并带机型手写标注。",
            localizedSuitableScenes: ["朋友", "餐桌", "旅行"]
        ),
        FilmPreset(
            id: "sx-fade",
            name: "SX Fade",
            shortName: "SX",
            iso: 160,
            description: "A faded instant look with pastel color, soft focus impression, and warm ivory frame.",
            suitableScenes: ["Home", "Flowers", "Selfie"],
            exposureBias: 0.12,
            temperatureShift: 340,
            tintShift: 10,
            contrast: 0.78,
            brightness: 0.03,
            saturation: 0.78,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.08),
                p1: CurvePoint(x: 0.25, y: 0.27),
                p2: CurvePoint(x: 0.50, y: 0.54),
                p3: CurvePoint(x: 0.82, y: 0.82),
                p4: CurvePoint(x: 1.00, y: 0.92)
            ),
            grainAmount: 0.16,
            grainSize: 1.6,
            vignetteAmount: 0.10,
            halationAmount: 0.12,
            lightLeakAmount: 0.02,
            timestampColorHex: "#96724D",
            borderStyle: .instant,
            localizedName: "SX 褪色即影",
            localizedShortName: "SX",
            cameraName: "SX Instant",
            localizedCameraName: "SX 即影",
            category: .instant,
            localizedDescription: "褪色拍立得观感：粉彩色、柔焦感和暖象牙白相纸。",
            localizedSuitableScenes: ["居家", "花草", "自拍"]
        ),
        FilmPreset(
            id: "half-frame-diary",
            name: "Half Frame Diary",
            shortName: "Half",
            iso: 400,
            description: "A half-frame diary camera style with vertical composition, warm date color, and casual grain.",
            suitableScenes: ["Daily", "Travel", "Street"],
            exposureBias: 0.02,
            temperatureShift: 180,
            tintShift: 2,
            contrast: 1.06,
            brightness: 0.006,
            saturation: 1.02,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.22, y: 0.17),
                p2: CurvePoint(x: 0.50, y: 0.51),
                p3: CurvePoint(x: 0.79, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.23,
            grainSize: 1.1,
            vignetteAmount: 0.19,
            halationAmount: 0.05,
            lightLeakAmount: 0.07,
            timestampColorHex: "#D69343",
            borderStyle: .whiteFrame,
            localizedName: "半格日记",
            localizedShortName: "半格",
            cameraName: "Half Frame",
            localizedCameraName: "半格相机",
            category: .camera,
            localizedDescription: "半格日记相机风格：竖向构图、暖色日期戳和随性的颗粒。",
            localizedSuitableScenes: ["日常", "旅行", "街拍"]
        ),
        FilmPreset(
            id: "ektar-vivid-100",
            name: "Ektar Vivid 100",
            shortName: "Vivid 100",
            iso: 100,
            description: "A vivid fine-grain color negative style with clean skies, saturated reds, and crisp daylight contrast.",
            suitableScenes: ["Landscape", "Cars", "Daylight"],
            exposureBias: -0.01,
            temperatureShift: 90,
            tintShift: 3,
            contrast: 1.18,
            brightness: 0.0,
            saturation: 1.26,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.01),
                p1: CurvePoint(x: 0.18, y: 0.13),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.89),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.10,
            grainSize: 0.85,
            vignetteAmount: 0.10,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D08B33",
            borderStyle: .none,
            localizedName: "鲜艳彩负 100",
            localizedShortName: "鲜艳100",
            cameraName: "Daylight Negative",
            localizedCameraName: "日光彩负",
            category: .negative,
            localizedDescription: "细颗粒高饱和彩负：天空干净、红色饱满、日光反差清晰。",
            localizedSuitableScenes: ["风景", "汽车", "日光"]
        ),
        FilmPreset(
            id: "tri-x-street",
            name: "Tri-X Street",
            shortName: "Tri-X",
            iso: 400,
            description: "A classic black-and-white street roll with punchy contrast, bright whites, and gritty midtones.",
            suitableScenes: ["Street", "Documentary", "Rain"],
            exposureBias: -0.04,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.34,
            brightness: -0.004,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.015),
                p1: CurvePoint(x: 0.18, y: 0.10),
                p2: CurvePoint(x: 0.48, y: 0.48),
                p3: CurvePoint(x: 0.77, y: 0.91),
                p4: CurvePoint(x: 1.00, y: 0.995)
            ),
            grainAmount: 0.38,
            grainSize: 1.35,
            vignetteAmount: 0.20,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D8D0C1",
            borderStyle: .paper,
            localizedName: "Tri-X 街头",
            localizedShortName: "Tri-X",
            cameraName: "Street SLR",
            localizedCameraName: "街头单反",
            category: .blackWhite,
            localizedDescription: "经典黑白街拍卷：反差有力、白位明亮、中间调粗粝。",
            localizedSuitableScenes: ["街拍", "纪实", "雨天"]
        ),
        FilmPreset(
            id: "cyber-ccd-blue",
            name: "Cyber CCD Blue",
            shortName: "CCD Blue",
            iso: 200,
            description: "A pocket digital CCD style with blue highlights, clipped flash whites, and early-2000s directness.",
            suitableScenes: ["Campus", "Flash", "Night"],
            exposureBias: 0.18,
            temperatureShift: -520,
            tintShift: -6,
            contrast: 1.28,
            brightness: 0.006,
            saturation: 0.86,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.00),
                p1: CurvePoint(x: 0.18, y: 0.12),
                p2: CurvePoint(x: 0.48, y: 0.50),
                p3: CurvePoint(x: 0.76, y: 0.92),
                p4: CurvePoint(x: 1.00, y: 1.00)
            ),
            grainAmount: 0.08,
            grainSize: 0.8,
            vignetteAmount: 0.06,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#BFD8E5",
            borderStyle: .none,
            localizedName: "蓝调 CCD",
            localizedShortName: "CCD 蓝",
            cameraName: "Cyber CCD",
            localizedCameraName: "蓝调 CCD",
            category: .digital,
            localizedDescription: "袖珍 CCD 数码感：蓝色高光、闪光灯白位截断、2000 年代直给感。",
            localizedSuitableScenes: ["校园", "闪光", "夜晚"]
        ),
        FilmPreset(
            id: "superia-green",
            name: "Superia Green",
            shortName: "Superia",
            iso: 400,
            description: "A consumer color roll with green shadows, lively blues, and bright vacation snapshots.",
            suitableScenes: ["Travel", "Beach", "Everyday"],
            exposureBias: 0.05,
            temperatureShift: -80,
            tintShift: -10,
            contrast: 1.10,
            brightness: 0.008,
            saturation: 1.16,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.025),
                p1: CurvePoint(x: 0.20, y: 0.16),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.78, y: 0.87),
                p4: CurvePoint(x: 1.00, y: 0.985)
            ),
            grainAmount: 0.24,
            grainSize: 1.1,
            vignetteAmount: 0.18,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#E0A14A",
            borderStyle: .none,
            localizedName: "Superia 绿调",
            localizedShortName: "绿调",
            cameraName: "Consumer 35",
            localizedCameraName: "家用 35mm",
            category: .negative,
            localizedDescription: "家用彩负感：绿色阴影、蓝色活泼、明亮度假快照。",
            localizedSuitableScenes: ["旅行", "海边", "日常"]
        ),
        FilmPreset(
            id: "noir-soft",
            name: "Noir Soft",
            shortName: "Noir",
            iso: 1600,
            description: "A soft monochrome night roll with glowing highlights, lowered clarity, and cinematic shadows.",
            suitableScenes: ["Night", "Portrait", "Window"],
            exposureBias: 0.06,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.08,
            brightness: 0.01,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.05),
                p1: CurvePoint(x: 0.24, y: 0.19),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.82, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.44,
            grainSize: 1.65,
            vignetteAmount: 0.28,
            halationAmount: 0.16,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D0C8BB",
            borderStyle: .paper,
            localizedName: "柔黑夜色",
            localizedShortName: "柔黑",
            cameraName: "Noir 1600",
            localizedCameraName: "黑白夜卷",
            category: .blackWhite,
            localizedDescription: "柔和黑白夜景卷：高光发光、清晰度降低、电影感阴影。",
            localizedSuitableScenes: ["夜晚", "人像", "窗边"]
        )
    ]
}
