import Foundation

struct FilmLibrary {
    let presets: [FilmPreset] = [
        FilmPreset(
            id: "sunlit-gold-200",
            name: "Sunlit Gold 200",
            shortName: "Gold 200",
            iso: 200,
            description: "A warm everyday color roll with soft contrast, gentle yellows, and clean daylight skin tones.",
            suitableScenes: ["Daylight", "Travel", "Everyday"],
            exposureBias: 0.08,
            temperatureShift: 420,
            tintShift: 6,
            contrast: 1.08,
            brightness: 0.01,
            saturation: 1.08,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.22, y: 0.18),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.78, y: 0.84),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.16,
            grainSize: 1.0,
            vignetteAmount: 0.18,
            halationAmount: 0.05,
            lightLeakAmount: 0.0,
            timestampColorHex: "#E2A34F",
            borderStyle: .none
        ),
        FilmPreset(
            id: "soft-portrait-400",
            name: "Soft Portrait 400",
            shortName: "Portrait 400",
            iso: 400,
            description: "Low-contrast color negative look with lifted shadows, calm highlights, and forgiving skin tones.",
            suitableScenes: ["Portrait", "Cloudy", "Indoor"],
            exposureBias: 0.04,
            temperatureShift: 180,
            tintShift: 8,
            contrast: 0.94,
            brightness: 0.012,
            saturation: 0.96,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.04),
                p1: CurvePoint(x: 0.24, y: 0.23),
                p2: CurvePoint(x: 0.50, y: 0.52),
                p3: CurvePoint(x: 0.82, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.20,
            grainSize: 1.1,
            vignetteAmount: 0.12,
            halationAmount: 0.04,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D7A56D",
            borderStyle: .none
        ),
        FilmPreset(
            id: "silver-hp5",
            name: "Silver HP5",
            shortName: "HP5",
            iso: 400,
            description: "A monochrome documentary roll with visible grain, crisp midtones, and tactile shadows.",
            suitableScenes: ["Street", "Architecture", "Documentary"],
            exposureBias: -0.02,
            temperatureShift: 0,
            tintShift: 0,
            contrast: 1.22,
            brightness: 0.0,
            saturation: 0.0,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.20, y: 0.13),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.31,
            grainSize: 1.45,
            vignetteAmount: 0.24,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D9D2C6",
            borderStyle: .paper
        ),
        FilmPreset(
            id: "green-street-400",
            name: "Green Street 400",
            shortName: "Street 400",
            iso: 400,
            description: "A cooler city roll with green-cyan shadows, punchier contrast, and a documentary street feel.",
            suitableScenes: ["Street", "Cloudy", "City"],
            exposureBias: -0.03,
            temperatureShift: -220,
            tintShift: -7,
            contrast: 1.13,
            brightness: -0.006,
            saturation: 1.03,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.02),
                p1: CurvePoint(x: 0.22, y: 0.16),
                p2: CurvePoint(x: 0.50, y: 0.49),
                p3: CurvePoint(x: 0.78, y: 0.86),
                p4: CurvePoint(x: 1.00, y: 0.98)
            ),
            grainAmount: 0.22,
            grainSize: 1.05,
            vignetteAmount: 0.20,
            halationAmount: 0.03,
            lightLeakAmount: 0.0,
            timestampColorHex: "#D8A24A",
            borderStyle: .none
        ),
        FilmPreset(
            id: "tungsten-800",
            name: "Tungsten 800",
            shortName: "Tungsten",
            iso: 800,
            description: "A night roll for neon, tungsten interiors, and red-orange highlight bloom.",
            suitableScenes: ["Night", "Neon", "Indoor"],
            exposureBias: 0.10,
            temperatureShift: -520,
            tintShift: 12,
            contrast: 1.08,
            brightness: 0.004,
            saturation: 1.12,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.04),
                p1: CurvePoint(x: 0.24, y: 0.18),
                p2: CurvePoint(x: 0.50, y: 0.50),
                p3: CurvePoint(x: 0.80, y: 0.88),
                p4: CurvePoint(x: 1.00, y: 0.97)
            ),
            grainAmount: 0.36,
            grainSize: 1.4,
            vignetteAmount: 0.22,
            halationAmount: 0.42,
            lightLeakAmount: 0.02,
            timestampColorHex: "#E07A4B",
            borderStyle: .none
        ),
        FilmPreset(
            id: "pocket-flash",
            name: "Pocket Flash",
            shortName: "Flash",
            iso: 400,
            description: "A compact disposable-camera look with hard contrast, casual saturation, and occasional edge leak.",
            suitableScenes: ["Party", "Friends", "Snapshot"],
            exposureBias: 0.12,
            temperatureShift: 260,
            tintShift: 2,
            contrast: 1.18,
            brightness: 0.018,
            saturation: 1.18,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.03),
                p1: CurvePoint(x: 0.18, y: 0.12),
                p2: CurvePoint(x: 0.48, y: 0.51),
                p3: CurvePoint(x: 0.78, y: 0.90),
                p4: CurvePoint(x: 1.00, y: 0.99)
            ),
            grainAmount: 0.28,
            grainSize: 1.2,
            vignetteAmount: 0.30,
            halationAmount: 0.12,
            lightLeakAmount: 0.34,
            timestampColorHex: "#EE9D3D",
            borderStyle: .none
        ),
        FilmPreset(
            id: "ccd-2003",
            name: "CCD 2003",
            shortName: "CCD",
            iso: 160,
            description: "A clean early-digital compact camera mood with cool whites, clipped highlights, and direct color.",
            suitableScenes: ["Campus", "Indoor", "Daily"],
            exposureBias: 0.16,
            temperatureShift: -340,
            tintShift: -4,
            contrast: 1.20,
            brightness: 0.012,
            saturation: 0.92,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.00),
                p1: CurvePoint(x: 0.20, y: 0.14),
                p2: CurvePoint(x: 0.48, y: 0.50),
                p3: CurvePoint(x: 0.78, y: 0.91),
                p4: CurvePoint(x: 1.00, y: 1.00)
            ),
            grainAmount: 0.10,
            grainSize: 0.8,
            vignetteAmount: 0.08,
            halationAmount: 0.0,
            lightLeakAmount: 0.0,
            timestampColorHex: "#C8D6DA",
            borderStyle: .none
        ),
        FilmPreset(
            id: "instant-square",
            name: "Instant Square",
            shortName: "Instant",
            iso: 640,
            description: "A soft instant-photo preset with square framing, warm paper border, and relaxed contrast.",
            suitableScenes: ["Still Life", "Selfie", "Home"],
            exposureBias: 0.06,
            temperatureShift: 240,
            tintShift: 5,
            contrast: 0.88,
            brightness: 0.02,
            saturation: 0.90,
            toneCurve: ToneCurvePreset(
                p0: CurvePoint(x: 0.00, y: 0.05),
                p1: CurvePoint(x: 0.22, y: 0.23),
                p2: CurvePoint(x: 0.50, y: 0.53),
                p3: CurvePoint(x: 0.82, y: 0.85),
                p4: CurvePoint(x: 1.00, y: 0.96)
            ),
            grainAmount: 0.18,
            grainSize: 1.35,
            vignetteAmount: 0.16,
            halationAmount: 0.06,
            lightLeakAmount: 0.03,
            timestampColorHex: "#9F7B4E",
            borderStyle: .instant
        )
    ]
}
